MVC-CRUD/MVC/Models/ProductInfo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInfo
    {
        public int pid { get; set; }
        public string pname { get; set; }
        public Nullable<decimal> price { get; set; }
        public string content { get; set; }
        public string img { get; set; }
        public string ptid { get; set; }
    
        public virtual ProductType ProductType { get; set; }
    }
}

MVC-CRUD/MVC/Controllers/ProductInfoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class ProductInfoController : Controller
    {
        // GET: ProductInfo
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 上传图片视图
        /// </summary>
        /// <returns></returns>
        public ActionResult Edit()
        {
            return View();
        }
        /// <summary>
        /// 单图上传图片
        /// </summary>
        /// <returns></returns>
        public string NewSave()
        {
            // 设置一个返回值
            var imageurl = "";
            //2、获取文件对象
            HttpFileCollectionBase files = Request.Files;
            HttpPostedFileBase file = files["File"];
            string FileName = file.FileName;
            string guid1 = "";
            //3、判断是否为空
            if (FileName!=null&& FileName!="")
            {
                //4、截取文件后缀
                string FileType = FileName.Substring(FileName.LastIndexOf(".") + 1); //得到文件的后缀名
                if (FileType.ToLower()=="jpg"|| FileType.ToLower() == "png"||FileType.ToLower()== "jfif")
                {
                    if (file.ContentLength< 5 * 1024 * 1024)
                    {
                    guid1 = System.Guid.NewGuid().ToString() + "." + FileType; //得到重命名的文件名
                    // 5、替换guid的-为空 并保存
                    var guid = guid1.Replace("-", "");
                    file.SaveAs(Server.MapPath("/Upload/") + guid); //保存操作
                    string Upload = "/Upload/" + guid;
                    imageurl = Upload;
                    }
                    else
                    {
                        return "文件大小超出限制!";
                    }
                }
                else
                {
                    return "请选择jpg png jfif后缀的图片！";
                }
            }
            else
            {
                return "上传失败！";
            }
            return imageurl; //成功返回保存后的文件路径
        }
        /// <summary>
        /// 多图上传
        /// </summary>
        /// <returns></returns>
        public bool NewSaves()
        {
            var guid = "";
            var list = Request.Files.GetMultiple("File");
            if (list[0].FileName!="" && list[0].FileName !=null)
            {
                foreach (var item in list)
                {
                    string filename = item.FileName;
                    // 1、获取文件后缀名
                    FileInfo fileInfo = new FileInfo(filename);
                    string ext = fileInfo.Extension;
                    // 2、修改文件名
                    guid = Guid.NewGuid().ToString()+ ext;
                    // 3、替换guid的-为空 并保存
                    var guid1 = guid.Replace("-", "");
                    var path = Server.MapPath("/Upload/");
                    item.SaveAs(path + guid1);
                }
            }
            else
            {
                return false;
            }
            return true;
        }
        public bool NewAdd()
        {
            HttpFileCollectionBase files = Request.Files;
            HttpPostedFileBase file = files["File"];
            return true;
        }
    }
}

MVC-CRUD/MVC/Views/ProductInfo/Edit.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <style>
        #images {
            max-width: 150px;
            max-height: 150px;
        }
    </style>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/JS/ajaxfileupload.js"></script>
    <script src="~/Scripts/JS/html5ImgCompress.min.js"></script>
    <script>
        $(function () {
            //获取文档中 id="image" 的元素：
            var img = document.querySelector("#image");

            $("#image").change(function () {
                var file = this.files[0];
                var reader = new FileReader();
                reader.readAsDataURL(file);
                reader.onload = function () {
                    console.log(reader.result);
                    $("#images").attr('src', reader.result);
                }
            })
            // AJAX 上传图片
            $("#btn").click(function () {
                // var image = $("#image3").val();
                alert(1);
                $.ajaxFileUpload({
                    url: '@Url.Action("NewAdd", "ProductInfo")',
                    fileElementId: 'file1',
                    secureuri: false,
                    type: 'post',
                    success: function (res) {
                        console.log(res);
                    }
                })
            })
        })
    </script>

</head>
<body>
    <div>
        <form id="form1" method="post" action="@Url.Action("NewSa] -ppves","ProductInfo")" enctype="multipart/form-data">
            图片1：<input type="file" id="image" name="File" multiple /></br>
            图片2：<input type="file" id="image2" name="File" multiple /></br>
            <img src="" id="images" /></br>
            <input type="submit" value="上传" id="" />
        </form>
        <h2>AJAX上传图</h2>
        <input type="file" id="file1" name="File" />
        <input type="file" id="image5" name="File" />
        <button id="btn">上传</button>
    </div>
</body>
</html>